---
- name: Create Alertmanager Directory
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ alertmanager_data_directory }}/data"

- name: Copy Alertmanager config file
  template:
    src: alertmanager/alertmanager.yml
    dest: "{{ alertmanager_data_directory }}/alertmanager.yml"

- name: Alertmanager Docker Container
  docker_container:
    name: alertmanager
    image: quay.io/prometheus/alertmanager
    pull: true
    ports:
      - "{{ alertmanager_port }}:9093"
    volumes:
      - "{{ alertmanager_data_directory }}/data:/alertmanager:rw"
      - "{{ alertmanager_data_directory }}/alertmanager.yml:/etc/alertmanager/alertmanager.yml:rw"
    restart_policy: unless-stopped
    labels:
      traefik.backend: "alertmanager"
      traefik.frontend.rule: "Host:alertmanager.{{ ansible_nas_domain }}"
      traefik.enable: "{{ alertmanager_available_externally }}"
      traefik.port: "9093"
