groups:
- name: "Hardware"
  rules:
  - alert: Node down
    expr: up{job="{{ ansible_nas_hostname }}"} == 0
    for: 3m
    labels:
      severity: warning
    annotations:
      title: Node {{ '{{' }} {{ '$' }}labels.instance {{ '}}' }} is down
      summary: Failed to scrape {{ '{{' }} {{ '$' }}labels.job {{ '}}' }} on {{ '{{' }} {{ '$' }}labels.instance {{ '}}' }} for more than 3 minutes. Node seems down.
      message: Node {{ '{{' }} {{ '$' }}labels.instance {{ '}}' }} is down.\nFailed to scrape {{ '{{' }} {{ '$' }}labels.job {{ '}}' }} on {{ '{{' }} {{ '$' }}labels.instance {{ '}}' }} for more than 3 minutes.
