global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

{% if (prometheusnode_enabled | default(False)) %}
  - job_name: '{{ ansible_nas_hostname }}'
    static_configs:
    - targets: ['{{ ansible_nas_ip }}:{{ prometheusnode_port }}']

{% endif %}
{% if (cadvisor_enabled | default(False)) %}
  - job_name: cadvisor
    scrape_interval: 10s
    static_configs:
    - targets: ['{{ ansible_nas_ip }}:{{ cadvisor_port }}']

{% endif %}
{% if (cexporter_enabled | default(False)) %}
  - job_name: 'cexporter'
    static_configs:
    - targets: ['{{ ansible_nas_ip }}:{{ cexporter_port }}']

{% endif %}
{% if (alertmanager_enabled | default(False)) %}
{% if (prometheusnode_enabled | default(False)) %}
rule_files:
  - "alert.rules.yml"

{% endif %}
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - {{ ansible_nas_ip }}:{{ alertmanager_port }}
{% endif %}
